// ═══════════════════════════════════════════════════════════════════════════
//  THE CONTRACT — read-only. Do not edit this file.
// ═══════════════════════════════════════════════════════════════════════════
//
// This is the ENTIRE surface between your UI layer and the Mebelchi model. There
// is deliberately nothing else: no engine, no workshop profiles, no session model,
// no save path. If a change seems to need something that is not in here, it is a
// host-side change — ask, do not invent it.
//
// UNITS — the one rule that matters most:
//
//   Every number crossing this boundary is mm10 — TENTHS of a millimetre, integer.
//   16mm = 160.  600mm = 6000.
//
// Centimetres exist only in what the user reads on screen, and `ui/measure.ts` is
// the only place allowed to convert. Never introduce floats, never introduce a
// second unit. The host stores mm10 and the machine files are generated from it;
// a rounding error here becomes a wrong hole in a real cabinet door.

/** Fixed-point integer: tenths of a millimetre. */
export type mm10 = number;

/** What a panel IS. The host decides this; the UI only displays it. */
export type PartRole =
  | "side" | "bottom" | "top" | "stretcher" | "shelf" | "back" | "worktop"
  | "door" | "divider" | "plinth" | "filler";

/**
 * What a panel's own X and Y axes mean physically. A panel is always axis-aligned
 * to one of three principal planes; this says which. The renderer uses it to put
 * edge banding on the correct edges.
 */
export interface PartOrientation {
  xAxis: "width" | "height" | "depth";
  yAxis: "width" | "height" | "depth";
}

/**
 * One panel, ready to draw. Positions and extents are mm10 world coordinates.
 *
 * NOTE what is absent: there is no `thickness` field you may set. `depth` here is
 * already the resolved extent the host computed from the workshop profile. The UI
 * never decides a thickness — that is the core law of this product.
 */
export interface Panel {
  id: string;
  name: string;
  role: PartRole | "other";
  /** world min-corner */
  x: number;
  y: number;
  z: number;
  /** world extents; one of these is the profile-supplied thickness */
  width: number;
  height: number;
  depth: number;
  material: string;
  /** edge banding, SWJ008 face order [Ymax, Ymin, Xmax, Xmin] */
  bands?: [number, number, number, number];
  orientation?: PartOrientation;
  /** free rotation in RADIANS, applied on top of the axis-aligned plane */
  rx?: number;
  ry?: number;
  rz?: number;
}

/** A drilled hole, for rendering only. */
export interface Hole {
  id: string;
  x: number;
  y: number;
  z: number;
  diameter: number;
  depth: number;
  direction: "x" | "y" | "z";
}

// ── unit conversion. The ONLY conversions that exist. ──────────────────────

/** mm10 → metres, for Three.js. */
export function mm10ToMeters(value: mm10): number {
  return value / 10000;
}

/** mm10 → millimetres, for display. */
export function mm10ToMm(value: mm10): number {
  return value / 10;
}
